auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink:  /:categories/:title
paginate_path: "blog/page:num"

excerpt_separator:  <!--more-->

title: Across the universe
url: http://lynettelu.co
category: category_name
feed: /atom.xml
author_info: <a href="http://lynettelu.co/">Lynette Lu</a>
