auto: true

markdown: kramdown
highlighter: rouge
pygments: unset
paginate: 8
permalink:  /:categories/:title
paginate_path: "blog/page:num"

excerpt_separator:  <!--more-->

title: Sic itur ad astra
url: http://tothestar.co
category: category_name
feed: /atom.xml
author_info: <a href="http://lynettelu.github.io/">Lynette Lu</a>
