auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

excerpt_separator:"\n\n"

title: Across the universe
url: http://lynettelu.github.io
feed: /atom.xml
author_info: <a href="http://lynettelu.com/">Lynette Lu</a>
