auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: Lynette Lu's Blog
url: http://lynettelu.github.io
feed: /atom.xml
author_info: <a href="http://lynettelu.com/">Lynette Lu</a>
