auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink:  /:categories/:title
paginate_path: "blog/page:num"

excerpt_separator:  <!--more-->

title: Ad Astra
url: http://tothestar.co
category: category_name
feed: /atom.xml
author_info: <a href="http://lynettelu.github.io/">Lynette Lu</a>
